//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class AgeRange : BaseEntity<AgeRange>
    {
        [DataMember]
                    [Required(ErrorMessage="Id is required")]
    	public int Id
    	{ 
    		get { return _Id; }
    		set
    		{
    			if (Equals(value, _Id)) return;
    			_Id = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _Id;
        [DataMember]
                    [Required(ErrorMessage="Description is required")]
                [StringLength(50)]
    	public string Description
    	{ 
    		get { return _Description; }
    		set
    		{
    			if (Equals(value, _Description)) return;
    			_Description = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Description;
        [DataMember]
                    [Required(ErrorMessage="MinAge is required")]
    	public int MinAge
    	{ 
    		get { return _MinAge; }
    		set
    		{
    			if (Equals(value, _MinAge)) return;
    			_MinAge = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _MinAge;
        [DataMember]
                    [Required(ErrorMessage="MaxAge is required")]
    	public int MaxAge
    	{ 
    		get { return _MaxAge; }
    		set
    		{
    			if (Equals(value, _MaxAge)) return;
    			_MaxAge = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _MaxAge;
    }
}
