//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class ItemPresetDosage : BaseEntity<ItemPresetDosage>
    {
        [DataMember]
                    [Required(ErrorMessage="Id is required")]
    	public int Id
    	{ 
    		get { return _Id; }
    		set
    		{
    			if (Equals(value, _Id)) return;
    			_Id = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _Id;
        [DataMember]
                    [Required(ErrorMessage="Dosage is required")]
    	public string Dosage
    	{ 
    		get { return _Dosage; }
    		set
    		{
    			if (Equals(value, _Dosage)) return;
    			_Dosage = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Dosage;
        [DataMember]
                    [Required(ErrorMessage="ItemId is required")]
    	public int ItemId
    	{ 
    		get { return _ItemId; }
    		set
    		{
    			if (Equals(value, _ItemId)) return;
    			_ItemId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _ItemId;
        [DataMember]
    	public Item Item
    	{
    		get { return _Item; }
    		set
    		{
    			if (Equals(value, _Item)) return;
    			_Item = value;
    			ItemChangeTracker = _Item == null ? null
    				: new ChangeTrackingCollection<Item> { _Item };
    			NotifyPropertyChanged();
    		}
    	}
    	private Item _Item;
    	private ChangeTrackingCollection<Item> ItemChangeTracker { get; set; }
    }
}
