//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class PatientMembership : BaseEntity<PatientMembership>
    {
        [DataMember]
                    [Required(ErrorMessage="PatientId is required")]
    	public int PatientId
    	{ 
    		get { return _PatientId; }
    		set
    		{
    			if (Equals(value, _PatientId)) return;
    			_PatientId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _PatientId;
        [DataMember]
                    [Required(ErrorMessage="Points is required")]
    	public double Points
    	{ 
    		get { return _Points; }
    		set
    		{
    			if (Equals(value, _Points)) return;
    			_Points = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private double _Points;
        [DataMember]
                    [Required(ErrorMessage="Membership is required")]
                [StringLength(50)]
    	public string Membership
    	{ 
    		get { return _Membership; }
    		set
    		{
    			if (Equals(value, _Membership)) return;
    			_Membership = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Membership;
        [DataMember]
                    [Required(ErrorMessage="MembershipId is required")]
    	public int MembershipId
    	{ 
    		get { return _MembershipId; }
    		set
    		{
    			if (Equals(value, _MembershipId)) return;
    			_MembershipId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _MembershipId;
        [DataMember]
        	public Nullable<int> Age
    	{ 
    		get { return _Age; }
    		set
    		{
    			if (Equals(value, _Age)) return;
    			_Age = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<int> _Age;
        [DataMember]
    	public Patient Patient
    	{
    		get { return _Patient; }
    		set
    		{
    			if (Equals(value, _Patient)) return;
    			_Patient = value;
    			PatientChangeTracker = _Patient == null ? null
    				: new ChangeTrackingCollection<Patient> { _Patient };
    			NotifyPropertyChanged();
    		}
    	}
    	private Patient _Patient;
    	private ChangeTrackingCollection<Patient> PatientChangeTracker { get; set; }
    }
}
