//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class PatientRewardSale : BaseEntity<PatientRewardSale>
    {
        [DataMember]
                    [Required(ErrorMessage="Id is required")]
    	public int Id
    	{ 
    		get { return _Id; }
    		set
    		{
    			if (Equals(value, _Id)) return;
    			_Id = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _Id;
        [DataMember]
                    [StringLength(50)]
    	public string SalesReceptNumber
    	{ 
    		get { return _SalesReceptNumber; }
    		set
    		{
    			if (Equals(value, _SalesReceptNumber)) return;
    			_SalesReceptNumber = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _SalesReceptNumber;
        [DataMember]
                    [Required(ErrorMessage="SalesDate is required")]
    	public System.DateTime SalesDate
    	{ 
    		get { return _SalesDate; }
    		set
    		{
    			if (Equals(value, _SalesDate)) return;
    			_SalesDate = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private System.DateTime _SalesDate;
        [DataMember]
                    [Required(ErrorMessage="TrackingNumber is required")]
                [StringLength(50)]
    	public string TrackingNumber
    	{ 
    		get { return _TrackingNumber; }
    		set
    		{
    			if (Equals(value, _TrackingNumber)) return;
    			_TrackingNumber = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _TrackingNumber;
        [DataMember]
    	public PatientReward PatientReward
    	{
    		get { return _PatientReward; }
    		set
    		{
    			if (Equals(value, _PatientReward)) return;
    			_PatientReward = value;
    			PatientRewardChangeTracker = _PatientReward == null ? null
    				: new ChangeTrackingCollection<PatientReward> { _PatientReward };
    			NotifyPropertyChanged();
    		}
    	}
    	private PatientReward _PatientReward;
    	private ChangeTrackingCollection<PatientReward> PatientRewardChangeTracker { get; set; }
    }
}
