/*
Deployment script for QuickSales-Enterprise-Original

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;



GO
PRINT N'Altering Table [dbo].[Persons_Patient]...';


GO
ALTER TABLE [dbo].[Persons_Patient]
    ADD [CardId] NVARCHAR (50) NULL;


GO
PRINT N'Altering Table [dbo].[QBCustomer]...';


GO
ALTER TABLE [dbo].[QBCustomer]
    ADD [CustomerId] NVARCHAR (50) NULL;


GO
PRINT N'Refreshing View [dbo].[Patient History]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[Patient History]';


GO
PRINT N'Refreshing View [dbo].[PatientLifeTimeValue]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[PatientLifeTimeValue]';


GO
PRINT N'Refreshing View [dbo].[PatientMembership]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[PatientMembership]';


GO
PRINT N'Refreshing View [dbo].[PatientSales]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[PatientSales]';


GO
PRINT N'Refreshing View [dbo].[PatientView]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[PatientView]';


GO
PRINT N'Refreshing View [dbo].[SearchView]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SearchView]';


GO
PRINT N'Altering View [dbo].[IDCardInfo]...';


GO



ALTER VIEW [dbo].[IDCardInfo]
AS
SELECT Persons.Id as PatientId, Persons.FirstName, Persons.LastName, Persons.Address, Persons.PhoneNumber,
				coalesce(Persons_Patient.Cardid,
				cast(LEFT(Persons.FirstName, 1) + LEFT(Persons.LastName, 1) + LEFT(dbo.GetOnlyNumbers((CASE WHEN LEFT(persons.phonenumber, 3) = '473' THEN substring(Persons.PhoneNumber, 4, 7) ELSE persons.phonenumber END)), 7) as nvarchar(15))) AS CardId,
				 Persons_Patient.TotalSales, 
                 PatientMembership.Points, MembershipTypes.Name as Membership, MembershipTypes.EntrySalesAmount, MembershipTypes.MaxSalesAmount, MembershipTypes.PointRatePerDollar, MembershipTypes.Discount, 
                 MembershipTypes.QuickBooksPriceLevel, Company.Address AS Store, MembershipTypes.Id AS MembershipId
FROM    Persons INNER JOIN
                 Persons_Patient ON Persons.Id = Persons_Patient.Id INNER JOIN
                 PatientMembership ON Persons_Patient.Id = PatientMembership.PatientId INNER JOIN
                 MembershipTypes ON PatientMembership.MembershipId = MembershipTypes.Id CROSS JOIN
                 Company
GROUP BY Persons.Id, Persons.FirstName, Persons.LastName, Persons.Address, Persons.PhoneNumber, LEFT(Persons.FirstName, 1) + LEFT(Persons.LastName, 1) 
                 + LEFT(dbo.GetOnlyNumbers((CASE WHEN LEFT(persons.phonenumber, 3) = '473' THEN substring(Persons.PhoneNumber, 4, 7) ELSE persons.phonenumber END)), 7), Persons_Patient.TotalSales, 
                 PatientMembership.Points, MembershipTypes.Name, MembershipTypes.EntrySalesAmount, MembershipTypes.MaxSalesAmount, MembershipTypes.PointRatePerDollar, MembershipTypes.Discount, 
                 MembershipTypes.QuickBooksPriceLevel, Company.Address, MembershipTypes.Id, Persons_Patient.Cardid
GO
PRINT N'Refreshing View [dbo].[IDCardInfoData]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[IDCardInfoData]';


GO
PRINT N'Refreshing View [dbo].[PatientAvailableRewards]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[PatientAvailableRewards]';


GO
PRINT N'Creating View [dbo].[CardIdTobeUpdated]...';


GO

CREATE VIEW [dbo].[CardIdTobeUpdated]
AS
SELECT dbo.Persons_Patient.CardId, dbo.Persons_Patient.Id, dbo.QBCustomer.CustomerListID
FROM     dbo.Persons_Patient INNER JOIN
                  dbo.QBCustomer ON dbo.Persons_Patient.Id = dbo.QBCustomer.Id
WHERE  (dbo.Persons_Patient.CardId IS NOT NULL) and (dbo.Persons_Patient.CardId <> isnull(dbo.QBCustomer.CustomerID,'')) AND (dbo.Persons_Patient.CardId NOT IN
                      (SELECT ISNULL(CardId, '') AS Expr1
                       FROM      dbo.IDCardInfoData))

GO
PRINT N'Update complete.';


GO
