

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RMSDataAccessLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RMSModel : DbContext
{
    public RMSModel()
        : base("name=RMSModel")
    {

        this.Configuration.LazyLoadingEnabled = false;

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Item> Item { get; set; }

    public virtual DbSet<TransactionBase> TransactionBase { get; set; }

    public virtual DbSet<TransactionEntryBase> TransactionEntryBase { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<TransactionEntryItem> TransactionEntryItems { get; set; }

    public virtual DbSet<QBInventoryItem> QBInventoryItems { get; set; }

    public virtual DbSet<QBCustomer> QBCustomers { get; set; }

    public virtual DbSet<IDCardInfo> IDCardInfoes { get; set; }

    public virtual DbSet<QBSale> QBSales { get; set; }

    public virtual DbSet<QBSalesDetail> QBSalesDetails { get; set; }

    public virtual DbSet<PatientAvailableReward> PatientAvailableRewards { get; set; }

    public virtual DbSet<PatientRewardSale> PatientRewardSales { get; set; }

    public virtual DbSet<Store> Stores { get; set; }

    public virtual DbSet<MembershipType> MembershipTypes { get; set; }

    public virtual DbSet<PatientMembership> PatientMemberships { get; set; }

}

}

