//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class QBSale : BaseEntity<QBSale>
    {
        [DataMember]
                    [Required(ErrorMessage="Id is required")]
    	public int Id
    	{ 
    		get { return _Id; }
    		set
    		{
    			if (Equals(value, _Id)) return;
    			_Id = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _Id;
        [DataMember]
                    [Required(ErrorMessage="QBCustomerId is required")]
    	public int QBCustomerId
    	{ 
    		get { return _QBCustomerId; }
    		set
    		{
    			if (Equals(value, _QBCustomerId)) return;
    			_QBCustomerId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _QBCustomerId;
        [DataMember]
                    [Required(ErrorMessage="SalesRecieptNumber is required")]
                [StringLength(50)]
    	public string SalesRecieptNumber
    	{ 
    		get { return _SalesRecieptNumber; }
    		set
    		{
    			if (Equals(value, _SalesRecieptNumber)) return;
    			_SalesRecieptNumber = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _SalesRecieptNumber;
        [DataMember]
    	public QBCustomer QBCustomer
    	{
    		get { return _QBCustomer; }
    		set
    		{
    			if (Equals(value, _QBCustomer)) return;
    			_QBCustomer = value;
    			QBCustomerChangeTracker = _QBCustomer == null ? null
    				: new ChangeTrackingCollection<QBCustomer> { _QBCustomer };
    			NotifyPropertyChanged();
    		}
    	}
    	private QBCustomer _QBCustomer;
    	private ChangeTrackingCollection<QBCustomer> QBCustomerChangeTracker { get; set; }
        [DataMember]
    	public QBSalesDetail QBSalesDetail
    	{
    		get { return _QBSalesDetail; }
    		set
    		{
    			if (Equals(value, _QBSalesDetail)) return;
    			_QBSalesDetail = value;
    			QBSalesDetailChangeTracker = _QBSalesDetail == null ? null
    				: new ChangeTrackingCollection<QBSalesDetail> { _QBSalesDetail };
    			NotifyPropertyChanged();
    		}
    	}
    	private QBSalesDetail _QBSalesDetail;
    	private ChangeTrackingCollection<QBSalesDetail> QBSalesDetailChangeTracker { get; set; }
    }
}
